# 连接工厂使用的数据库索引。
spring:
  redis:
    # Redis服务器主机。
    host: 127.0.0.1
    # Redis服务器端口。
    port: 6379
    # 登录redis服务器的密码。
    password:
    # 连接工厂使用的数据库索引。
    database: 0
    # 以毫秒为单位的连接超时。
    timeout: 10000
    # 连接URL，将覆盖主机，端口和密码（用户将被忽略），例如：redis://user:password@example.com:6379
    url:
    # 启用SSL支持。
    ssl: false
    jedis:
      pool:
        # 池在给定时间可以分配的最大连接数。使用负值无限制。
        max-active: 200
        # 池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
        max-idle: 8
        # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
        max-wait: -1
        # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
        min-idle: 0
server:
  port: 8080
