server:
  port: 9090
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.2.130:9092
      # 配置消费者消息offset是否自动重置(消费者重连后能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: 192.168.2.130:9092
      # 发送的对象信息变为json格式
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false

kafka:
  topic:
    my-topic1: my-topic1
    my-topic2: my-topic2
